<?php

/*
 * 系统设置模型
 * model()创建一个模型对象
 * tableName()返回当前数据表的名字
 * CActiveRecord 是活跃记录，好多成熟框架都有此技术
 * 元宝
 */

class System extends CActiveRecord {
    /*
     * 返回当前模型对象的静态方法
     */

    public static function model($className = __CLASS__) {
        return parent::model($className);
    }

    /*
     * 返回当前模型的名字
     */

    public function tableName() {
        //xm 前缀去掉
        return '{{system}}';
    }

    /*
     * 实现验证
     */

    public function rules() {
        return array(
            array('money', 'required', 'message' => '请填写提现金额低于！'),
            array('money', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '提现金额只能填写数字！'),
            array('zc_rewards', 'required', 'message' => '请填写会员注册奖励！'),
            array('zc_rewards', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '会员注册奖励只能填写数字！'),
            array('fee', 'required', 'message' => '请填写手续费！'),
            array('hlb_exchange_money', 'required', 'message' => '请填写多少元宝换1元人民币！'),
            array('hlb_exchange_money', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '多少元宝换1元人民币只能填写数字！'),
            array('cash_rewards1', 'required', 'message' => '请填写提现金额在100<=x<300奖励！'),
            array('cash_rewards1', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '提现金额在100<=x<300奖励只能填写数字！'),
            array('cash_rewards2', 'required', 'message' => '请填写提现金额在300<=x<600奖励！'),
            array('cash_rewards2', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '提现金额在300<=x<600奖励只能填写数字！'),
            array('cash_rewards3', 'required', 'message' => '请填写提现金额在600<=x<800奖励！'),
            array('cash_rewards3', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '提现金额在600<=x<800奖励只能填写数字！'),
            array('cash_rewards4', 'required', 'message' => '请填写提现金额在800<=x<1000奖励！'),
            array('cash_rewards4', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '提现金额在800<=x<1000奖励只能填写数字！'),
            array('cash_rewards5', 'required', 'message' => '请填写提现金额在x>=1000奖励！'),
            array('cash_rewards5', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '提现金额在x>=1000奖励只能填写数字！'),
            array('game1', 'required', 'message' => '请填写试玩一级提成！'),
            array('game1', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '试玩一级提成只能填写数字！'),
            array('game2', 'required', 'message' => '请填写试玩二级提成！'),
            array('game2', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '试玩二级提成只能填写数字！'),
            array('game3', 'required', 'message' => '请填写试玩三级提成！'),
            array('game3', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '试玩三级提成只能填写数字！'),
            array('game4', 'required', 'message' => '请填写试玩四级提成！'),
            array('game4', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '试玩四级提成只能填写数字！'),
            array('captcha1', 'required', 'message' => '请填写打码一级提成'),
            array('captcha2', 'required', 'message' => '请填写打码二级提成！'),
            array('captcha3', 'required', 'message' => '请填写打码三级提成！'),
            array('captcha4', 'required', 'message' => '请填写打码四级提成'),
            array('tx1', 'required', 'message' => '请填写一级首次提现奖励！'),
            array('tx2', 'required', 'message' => '请填写二级首次提现奖励！'),
            array('tx3', 'required', 'message' => '请填写三级首次提现奖励！'),
            array('tx4', 'required', 'message' => '请填写四级首次提现奖励！'),
            array('10tx1', 'required', 'message' => '请填写一级满10元提现奖励！'),
            array('10tx2', 'required', 'message' => '请填写二级满10元提现奖励！'),
            array('10tx3', 'required', 'message' => '请填写三级满10元提现奖励！'),
            array('10tx4', 'required', 'message' => '请填写四级满10元提现奖励！'),
            array('30tx1', 'required', 'message' => '请填写一级满30元提现奖励！'),
            array('30tx2', 'required', 'message' => '请填写二级满30元提现奖励！'),
            array('30tx3', 'required', 'message' => '请填写三级满30元提现奖励！'),
            array('30tx4', 'required', 'message' => '请填写四级满30元提现奖励！'),
            array('50tx1', 'required', 'message' => '请填写一级满50元提现奖励！'),
            array('50tx2', 'required', 'message' => '请填写二级满50元提现奖励！'),
            array('50tx3', 'required', 'message' => '请填写三级满50元提现奖励！'),
            array('50tx4', 'required', 'message' => '请填写四级满50元提现奖励！'),
            array('100tx1', 'required', 'message' => '请填写一级满100元提现奖励！'),
            array('100tx2', 'required', 'message' => '请填写二级满100元提现奖励！'),
            array('100tx3', 'required', 'message' => '请填写三级满100元提现奖励！'),
            array('100tx4', 'required', 'message' => '请填写四级满100元提现奖励！'),
            array('friend1', 'required', 'message' => '请填写好友一级提成！'),
            array('friend2', 'required', 'message' => '请填写好友二级提成！'),
            array('friend3', 'required', 'message' => '请填写好友三级提成！'),
            array('friend4', 'required', 'message' => '请填写好友四级提成！'),
            array('first', 'required', 'message' => '请填写完善个人资料奖励！'),
            array('first', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '完善个人资料奖励只能填写数字！'),
            array('second', 'required', 'message' => '请填写绑定手机号奖励！'),
            array('second', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '绑定手机号奖励只能填写数字！'),
            array('thirdly', 'required', 'message' => '请填写验证邮箱奖励！'),
            array('thirdly', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '验证邮箱奖励只能填写数字！'),
            array('fourthly', 'required', 'message' => '请填写设置交易密码奖励！'),
            array('fourthly', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '设置交易密码奖励只能填写数字！'),
            array('fifty', 'required', 'message' => '请填写绑定支付方式奖励！'),
            array('fifty', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '绑定支付方式奖励只能填写数字！'),
            array('sign_rand_hlb', 'required', 'message' => '请填写会员元宝小于！'),
            array('sign_rand_hld', 'required', 'message' => '请填写会员金豆小于！'),
            array('zzgame1', 'required', 'message' => '请填写站长试玩一级提成！'),
            array('zzgame1', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '站长试玩一级提成只能填写数字！'),
            array('zzgame2', 'required', 'message' => '请填写站长试玩二级提成！'),
            array('zzgame2', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '站长试玩二级提成只能填写数字！'),
            array('zzgame3', 'required', 'message' => '请填写站长试玩三级提成！'),
            array('zzgame3', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '站长试玩三级提成只能填写数字！'),
            array('zzgame4', 'required', 'message' => '请填写站长试玩四级提成！'),
            array('zzgame4', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '站长试玩四级提成只能填写数字！'),
            array('zzexpad1', 'required', 'message' => '请填写站长体验一级提成！'),
            array('zzexpad1', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '站长体验一级提成只能填写数字！'),
            array('zzexpad2', 'required', 'message' => '请填写站长体验二级提成！'),
            array('zzexpad2', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '站长体验二级提成只能填写数字！'),
            array('zzexpad3', 'required', 'message' => '请填写站长体验三级提成！'),
            array('zzexpad3', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '站长体验三级提成只能填写数字！'),
            array('zzexpad4', 'required', 'message' => '请填写站长体验四级提成！'),
            array('zzexpad4', 'match', 'pattern' => '/^[0-9]*$/', 'message' => '站长体验四级提成只能填写数字！'),
            array('zzcaptcha1', 'required', 'message' => '请填写站长打码一级提成'),
            array('zzcaptcha2', 'required', 'message' => '请填写站长打码二级提成！'),
            array('zzcaptcha3', 'required', 'message' => '请填写站长打码三级提成！'),
            array('zzcaptcha4', 'required', 'message' => '请填写站长打码四级提成'),
            array('zztx1', 'required', 'message' => '请填写站长一级首次提现奖励！'),
            array('zztx2', 'required', 'message' => '请填写站长二级首次提现奖励！'),
            array('zztx3', 'required', 'message' => '请填写站长三级首次提现奖励！'),
            array('zztx4', 'required', 'message' => '请填写站长四级首次提现奖励！'),
            array('zz10tx1', 'required', 'message' => '请填写站长一级满10元提现奖励！'),
            array('zz10tx2', 'required', 'message' => '请填写站长二级满10元提现奖励！'),
            array('zz10tx3', 'required', 'message' => '请填写站长三级满10元提现奖励！'),
            array('zz10tx4', 'required', 'message' => '请填写站长四级满10元提现奖励！'),
            array('zz30tx1', 'required', 'message' => '请填写站长一级满30元提现奖励！'),
            array('zz30tx2', 'required', 'message' => '请填写站长二级满30元提现奖励！'),
            array('zz30tx3', 'required', 'message' => '请填写站长三级满30元提现奖励！'),
            array('zz30tx4', 'required', 'message' => '请填写站长四级满30元提现奖励！'),
            array('zz50tx1', 'required', 'message' => '请填写站长一级满50元提现奖励！'),
            array('zz50tx2', 'required', 'message' => '请填写站长二级满50元提现奖励！'),
            array('zz50tx3', 'required', 'message' => '请填写站长三级满50元提现奖励！'),
            array('zz50tx4', 'required', 'message' => '请填写站长四级满50元提现奖励！'),
            array('zz100tx1', 'required', 'message' => '请填写站长一级满100元提现奖励！'),
            array('zz100tx2', 'required', 'message' => '请填写站长二级满100元提现奖励！'),
            array('zz100tx3', 'required', 'message' => '请填写站长三级满100元提现奖励！'),
            array('zz100tx4', 'required', 'message' => '请填写站长四级满100元提现奖励！'),
            array('zzfriend1', 'required', 'message' => '请填写完善所有资料好友一级奖励！'),
            array('zzfriend2', 'required', 'message' => '请填写完善所有资料好友二级奖励！'),
            array('zzfriend3', 'required', 'message' => '请填写完善所有资料好友三级奖励！'),
            array('zzfriend4', 'required', 'message' => '请填写完善所有资料好友四级奖励！'),
            array('wage1', 'required', 'message' => '请填写推广工资满30万奖励！'),
            array('wage2', 'required', 'message' => '请填写推广工资满200万奖励！'),
            array('wage3', 'required', 'message' => '请填写推广工资满1000万奖励！'),
            array('wage4', 'required', 'message' => '请填写推广工资满3000万奖励！'),
            array('wage5', 'required', 'message' => '请填写推广工资满5000万奖励！'),
            array('bady1', 'required', 'message' => '请填写小于500万收益率！'),
            array('bady2', 'required', 'message' => '请填写小于500万收益率！'),
            array('bady3', 'required', 'message' => '请填写大于500万小于1000万收益率！'),
            array('bady4', 'required', 'message' => '请填写大于500万小于1000万收益率！'),
            array('bady5', 'required', 'message' => '请填写大于1000万收益率！'),
            array('bady6', 'required', 'message' => '请填写大于1000万收益率！'),
        );
    }

    /*
     * 对应标签名称
     */

    function attributeLabels() {
        return array(
            'money' => '提现金额低于',
            'fee' => '低于提现金额手续费',
            'hlb_exchange_money' => '元宝',
            'cash_rewards1' => '提现金额在100<=x<300奖励',
            'cash_rewards2' => '提现金额在300<=x<600奖励',
            'cash_rewards3' => '提现金额在600<=x<800奖励',
            'cash_rewards4' => '提现金额在800<=x<1000奖励',
            'cash_rewards5' => '提现金额在x>=1000奖励',
            'rankrewards_time' => '排名奖励发放时间',
            'friend1' => '完善所有资料好友一级奖励',
            'friend2' => '完善所有资料好友二级奖励',
            'friend3' => '完善所有资料好友三级奖励',
            'friend4' => '完善所有资料好友四级奖励',
            'game1' => '试玩一级提成',
            'game2' => '试玩二级提成',
            'game3' => '试玩三级提成',
            'game4' => '试玩四级提成',
            'captcha1' => '打码一级提成',
            'captcha2' => '打码二级提成',
            'captcha3' => '打码三级提成',
            'captcha4' => '打码四级提成',
            'tx1' => '首次提现一级奖励',
            'tx2' => '首次提现二级奖励',
            'tx3' => '首次提现三级奖励',
            'tx4' => '首次提现四级奖励',
            '10tx1' => '满10元提现一级奖励',
            '10tx2' => '满10元提现二级奖励',
            '10tx3' => '满10元提现三级奖励',
            '10tx4' => '满10元提现四级奖励',
            '30tx1' => '满30元提现一级奖励',
            '30tx2' => '满30元提现二级奖励',
            '30tx3' => '满30元提现三级奖励',
            '30tx4' => '满30元提现四级奖励',
            '50tx1' => '满50元提现一级奖励',
            '50tx2' => '满50元提现二级奖励',
            '50tx3' => '满50元提现三级奖励',
            '50tx4' => '满50元提现四级奖励',
            '100tx1' => '满100元提现一级奖励',
            '100tx2' => '满100元提现二级奖励',
            '100tx3' => '满100元提现三级奖励',
            '100tx4' => '满100元提现四级奖励',
            'first' => '完善个人资料奖励',
            'second' => '绑定手机号奖励',
            'thirdly' => '验证邮箱奖励',
            'fourthly' => '设置交易密码奖励',
            'fifty' => '绑定支付方式奖励',
            'zc_rewards' => '会员注册奖励',
            'sign_rand_hlb' => '会员元宝小于',
            'sign_rand_hld' => '会员金豆小于',
            'zzfriend1' => '完善所有资料站长好友一级奖励',
            'zzfriend2' => '完善所有资料站长好友二级奖励',
            'zzfriend3' => '完善所有资料站长好友三级奖励',
            'zzfriend4' => '完善所有资料站长好友四级奖励',
            'zzgame1' => '站长试玩一级提成',
            'zzgame2' => '站长试玩二级提成',
            'zzgame3' => '站长试玩三级提成',
            'zzgame4' => '站长试玩四级提成',
            'zzcaptcha1' => '站长打码一级提成',
            'zzcaptcha2' => '站长打码二级提成',
            'zzcaptcha3' => '站长打码三级提成',
            'zzcaptcha4' => '站长打码四级提成',
            'zztx1' => '站长首次提现一级奖励',
            'zztx2' => '站长首次提现二级奖励',
            'zztx3' => '站长首次提现三级奖励',
            'zztx4' => '站长首次提现四级奖励',
            'zz10tx1' => '站长满10元提现一级奖励',
            'zz10tx2' => '站长满10元提现二级奖励',
            'zz10tx3' => '站长满10元提现三级奖励',
            'zz10tx4' => '站长满10元提现四级奖励',
            'zz30tx1' => '站长满30元提现一级奖励',
            'zz30tx2' => '站长满30元提现二级奖励',
            'zz30tx3' => '站长满30元提现三级奖励',
            'zz30tx4' => '站长满30元提现四级奖励',
            'zz50tx1' => '站长满50元提现一级奖励',
            'zz50tx2' => '站长满50元提现二级奖励',
            'zz50tx3' => '站长满50元提现三级奖励',
            'zz50tx4' => '站长满50元提现四级奖励',
            'zz100tx1' => '站长满100元提现一级奖励',
            'zz100tx2' => '站长满100元提现二级奖励',
            'zz100tx3' => '站长满100元提现三级奖励',
            'zz100tx4' => '站长满100元提现四级奖励',
            'wage1' => '推广工资满30万奖励',
            'wage2' => '推广工资满200万奖励',
            'wage3' => '推广工资满1000万奖励',
            'wage4' => '推广工资满3000万奖励',
            'wage5' => '推广工资满5000万奖励',
        );
    }

}
