<content>
  <CuPlayerWidth>600</CuPlayerWidth>
  <CuPlayerHeight>400</CuPlayerHeight>
  <CuPlayerAutoPlay>yes</CuPlayerAutoPlay>    
  <CuPlayerImage>images/start.jpg</CuPlayerImage>
<CuPlayerLogo>images/Logo.png</CuPlayerLogo>
<CuPlayerPosition>top-right</CuPlayerPosition>
  <CuPlayerFile>http://demo.cuplayer.com/file/test.mp4</CuPlayerFile>
</content>